# Generated by Django 2.1.5 on 2019-04-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaid', models.IntegerField(db_column='AreaID', primary_key=True, serialize=False)),
                ('areaname', models.CharField(blank=True, db_column='AreaName', max_length=200, null=True)),
                ('areatype', models.IntegerField(blank=True, db_column='AreaType', null=True)),
            ],
            options={
                'db_table': 'Area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bigcate',
            fields=[
                ('onlyid', models.AutoField(db_column='OnlyID', primary_key=True, serialize=False)),
                ('cateid', models.IntegerField(db_column='CateID')),
                ('catename', models.CharField(blank=True, db_column='CateName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'BigCate',
                'managed': False,
            },
        ),
    ]
