# Generated by Django 2.1.5 on 2019-04-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('onlyid', models.IntegerField(auto_created=True, db_column='OnlyID')),
                ('cabinetid', models.IntegerField(db_column='CabinetID', primary_key=True, serialize=False)),
                ('guid', models.CharField(db_column='GUID', max_length=100)),
                ('cabinetname', models.CharField(blank=True, db_column='CabinetName', max_length=50, null=True)),
                ('cabinetnetaddress', models.CharField(blank=True, db_column='CabinetNetAddress', max_length=50, null=True)),
                ('cabinetrows', models.IntegerField(blank=True, db_column='CabinetRows', null=True)),
                ('cabinetcolumns', models.IntegerField(blank=True, db_column='CabinetColumns', null=True)),
                ('backkeytime1', models.CharField(blank=True, db_column='BackKeyTime1', max_length=50, null=True)),
                ('backkeytime2', models.CharField(blank=True, db_column='BackKeyTime2', max_length=50, null=True)),
                ('backkeytime3', models.CharField(blank=True, db_column='BackKeyTime3', max_length=50, null=True)),
                ('areaid', models.IntegerField(db_column='AreaID')),
                ('communicationstate', models.IntegerField(db_column='CommunicationState')),
            ],
            options={
                'db_table': 'Cabinet',
                'managed': False,
            },
        ),
    ]
